Add Spanish translation for the Terms of Service
liberapay/liberapay.com pull request #1981
Opened 2021-03-07 20:27 UTC by Panquesito7

Things added/changed:

- Add Spanish translation for the [Terms of Service](https://github.com/liberapay/liberapay.com/tree/master/i18n/terms).

2021-03-08 08:48 UTC, jorgesumle reviewed
The translation is not the greatest, maybe I can review it later.

2021-03-08 08:48 UTC, jorgesumle commented on i18n/terms/es.md
> +persona que se inscribe en su servicio homónimo en lo sucesivo conocido como "el
la persona

2021-03-17 21:31 UTC, Panquesito7 commented
@trebmuh, would you mind reviewing this PR? Thanks. 🙂

2021-03-17 21:40 UTC, trebmuh commented
Unfortunately, I don't speak Spanish.

2021-03-22 13:03 UTC, jorgesumle requested changes

2021-03-22 21:19 UTC, Panquesito7 commented
All mentioned issues should be fixed now. Thanks for your review and comments. 🙂

2021-04-21 16:26 UTC, jorgesumle commented
> All mentioned issues should be fixed now. Thanks for your review and comments. slightly_smiling_face

Not really, it should say «perderán» (*con tilde en la a*), you haven't fixed that.

2021-04-21 16:39 UTC, Panquesito7 commented
> it should say «perderán»

Fixed now. Thanks.

2021-05-09 08:05 UTC, merged