Resolving Issue #463: Income is not easily divisible
liberapay/liberapay.com pull request #2000
Opened 2021-04-20 00:35 UTC by mhogara

**Problem:** As described in issue 463, previously, incorrect rounding could lead to one single team member getting a significantly different amount each week. 

**Solution:** We changed a call (within resolve_takes) to resolve_amounts to generally better distribute takes. We also made a specific if statement that checks for the specific case described in the original issue report and randomly selects a team member to get one single extra cent each week. 
The random selection required importing the random library and adding a large section of code in resolve_amounts. An alternative solution could be giving the same team member one extra cent every week. This is still an improvement on the original problem as the net difference between takes is only the minimum currency value(i.e. one cent). Let us know in reviews if this non randomized version is a preferred solution. 

**Overview of changes:** Added test in test_payday, added call in payday.py, changed values in resolve_takes to match currencies, randomized extra cent distribution in resolve_amounts

2021-04-20 01:48 UTC, mhogara commented
Saw that this failed the Travis CI build- will work on fixing those bugs shortly, but it appears to be mainly formatting errors.

2021-04-20 16:12 UTC, Changaco requested changes
The member who gets the extra cent shouldn't be selected randomly, because that's unstable. A relatively simple solution is to use the ID of the ~~latest or~~ next payday instead.

Also, please preserve the formatting of the code you're modifying, including the grouping and ordering of the imports.

2021-04-21 00:41 UTC, mhogara commented
An update: We have successfully fixed all the formatting errors and tried to match original imports as much as possible.

In terms of using the ID of the latest to distribute the extra cent, does that mean the ID of the next member of the team?  In the case of our test file, this would be the "jillian" each time. If this is not what you mean, please elaborate on what "ID of latest or next payday" is referring to so we can make sure our implementation matches your review.

2021-04-21 09:25 UTC, Changaco commented
The ID of the next payday is basically the number of weeks since Liberapay was launched. Right now it's 272, and later today it will be 273.

This number will have to be passed to the `Payday.resolve_takes` method as a `payday_id` argument. It can be obtained like this:

```python
next_payday_id = cursor.one("""
    SELECT id
      FROM paydays
     WHERE ts_start IS NOT NULL
  ORDER BY id DESC
     LIMIT 1
""", default=0) + 1
```

2021-04-22 19:41 UTC, mhogara commented
Alright, so to be clear in the proposed solution we would use ID of the next payday mod-ed by the number of team members to choose who gets the extra cent- that way it would change every week and cycle through each member. Let me know if this understanding is correct.

2021-04-23 07:24 UTC, Changaco commented
@mhogara You understood correctly.

2021-05-03 14:33 UTC, Changaco commented
@mhogara Are you still working on this?

2021-05-04 00:28 UTC, mhogara commented
Yes we are; sorry for the delay, we were busy with final exams for a few weeks, but do plan on finishing this up soon.

2021-05-06 01:54 UTC, closed without merging

2021-05-07 10:00 UTC, Changaco commented
@lewjs16 @mhogara No worries. Good luck with your new jobs. :slightly_smiling_face: