added public_name search function
liberapay/liberapay.com pull request #2164
Opened 2022-07-14 16:42 UTC by biskwikman

closes #2082 

I basically mimicked the structure of the code for usernames, but pointed the new query to the `public_name` column of the `participants` table, it seems to work fine.

2022-07-15 12:33 UTC, Changaco requested changes
I think it's probably better to have a single query and unified results section for both usernames and public names.

Also, a new [trigram index](https://www.postgresql.org/docs/current/pgtrgm.html) is needed on the `public_name` column to speed up the search:

```sql
CREATE INDEX public_name_trgm_idx ON participants
    USING GIN (lower(public_name) gin_trgm_ops)
    WHERE status = 'active'
      AND public_name IS NOT null;
```

2022-07-19 16:03 UTC, biskwikman commented
Should we include the username and public name under the avatar on all search results from now on? I think it would help with any confusion if an account has a similar username and public name.

2022-07-19 16:25 UTC, Changaco commented
Yes, both names should be displayed for all results.

2022-08-14 13:18 UTC, biskwikman commented
I've made it so the username and public name are returned in a single query, and both are displayed. I also added the index.

I'm not sure what word to use instead of "username" now. For example in the phrasing "Found a matching username". I was thinking of just using "user", but maybe "individual" would be more consistent.

2022-08-19 11:18 UTC, Changaco requested changes

2022-08-19 11:18 UTC, Changaco commented on www/search.spt
> +               AND NOT username like '~%%'
This is incorrect due to the order of precedence of the boolean operators. `… OR … AND …` is equivalent to `… OR ( … AND … )`, but here you wanted `( … OR … ) AND …`.

Also, you forgot to add `public_name IS NOT NULL`, so the query isn't using the new index.

```suggestion
             WHERE status = 'active'
               AND hide_from_search = 0
               AND ( NOT username like '~%%' AND lower(username) %% lower(%(q)s)
                     OR
                     public_name IS NOT NULL AND lower(public_name) %% lower(%(q)s)
                   )
```

2022-08-19 11:18 UTC, Changaco commented on www/search.spt
> +                    END AS rank
```suggestion
                 , greatest(
                       similarity(username, %(q)s),
                       similarity(public_name, %(q)s)
                   ) AS rank
```

2022-08-25 07:49 UTC, biskwikman commented
thanks for the suggestions. I just wanted to check, the tests will have to be updated for this, right? It looks like two are failing now.

2022-08-25 09:45 UTC, Changaco commented
The tests aren't failing with the latest commit. I think GitHub is still showing earlier test results because there's currently a merge conflict (because #2177 hasn't been deployed yet, because I've been waiting for new machine and human translations (https://github.com/liberapay/salon/issues/520)).

2024-07-15 09:15 UTC, Changaco commented
Sorry I let this linger for two years. It's now merged (#2401) and will be deployed this week.

2024-07-15 09:15 UTC, closed without merging